import { __assign } from "tslib";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Fragment, useRef } from "react";
import { Dialog, Transition } from "@headlessui/react";
export var ImageModal = function (_a) {
    var open = _a.open, setOpen = _a.setOpen, image = _a.image;
    var cancelButtonRef = useRef(null);
    return (_jsx(Transition.Root, __assign({ show: open, as: Fragment }, { children: _jsx(Dialog, __assign({ as: "div", className: "fixed inset-0 z-10 cursor-zoom-out overflow-y-auto", initialFocus: cancelButtonRef, onClose: setOpen }, { children: _jsxs("div", __assign({ className: "block min-h-screen px-4 text-center", ref: cancelButtonRef }, { children: [_jsx(Transition.Child, __assign({ as: Fragment, enter: "ease-out duration-300", enterFrom: "opacity-0", enterTo: "opacity-100", leave: "ease-in duration-200", leaveFrom: "opacity-100", leaveTo: "opacity-0" }, { children: _jsx(Dialog.Overlay, { className: "transition-opacity fixed inset-0 bg-gray-700 bg-opacity-75" }) })), _jsx("span", __assign({ className: "inline-block h-screen align-middle", "aria-hidden": "true" }, { children: "\u200B" })), _jsx(Transition.Child, __assign({ as: Fragment, enter: "ease-out duration-300", enterFrom: "opacity-0 translate-y-4 translate-y-0 scale-95", enterTo: "opacity-100 translate-y-0 scale-100", leave: "ease-in duration-200", leaveFrom: "opacity-100 translate-y-0 scale-100", leaveTo: "opacity-0 translate-y-4 translate-y-0 scale-95" }, { children: _jsx("div", __assign({ className: "transition-all inline-block max-h-screen max-w-7xl transform align-middle shadow-xl", onClick: function () { return setOpen(false); } }, { children: _jsx("img", __assign({}, image, { className: "max-h-screen max-w-full" })) })) }))] })) })) })));
};
//# sourceMappingURL=ImageModal.js.map